const pages = {
  ru: [
    ["✦ Добро пожаловать", "<p>General — место для создания тем и настройки бота. Рабочая тема — разговор с агентом OpenCodez.</p><blockquote>Нажми <b>Новая тема</b>, проверь название и модель, создай тему и начни писать.</blockquote><p>Название по умолчанию — случайное древнерусское слово. «Другое слово» выбирает заново, «Название» позволяет вписать своё. Режим отключается в Настройках.</p><p>FILES собирает файлы. AUDIO превращает голосовые и аудиофайлы в текст. Эти подключения можно закончить позже.</p>"],
    ["🎛 Темы и профили", "<p>Профиль сохраняет модель, reasoning и при необходимости System и агента. Создавай, копируй и изменяй профили в General → Профили.</p><p>Каталог берётся с выбранного сервера OpenCodez. Модели сгруппированы по провайдеру и семейству. Поиск понимает название и ID.</p><blockquote>Сохранение профиля не меняет уже работающие сессии. Новые темы используют выбранные настройки.</blockquote><p><code>/new</code> открывает мастер. <code>/new sol Название</code> остаётся быстрым способом создания.</p>"],
    ["💬 Ежедневная работа", "<p>Пиши задачу прямо в теме. Изображения и файлы можно приложить к сообщению. Файлы без подписи ждут следующего текстового сообщения.</p><table striped compact><tr><th>Команда</th><th>Действие</th></tr><tr><td>/session</td><td>Модель, состояние и ссылка на OpenCodez</td></tr><tr><td>/q задача</td><td>Отправить задачу или добавить в очередь</td></tr><tr><td>/q status</td><td>Посмотреть очередь</td></tr><tr><td>/kill</td><td>Остановить работу и очистить очередь</td></tr><tr><td>/compact</td><td>Сжать контекст завершённой сессии</td></tr></table><p>Бот показывает сообщения агента и результат. Обычные действия инструментов скрыты по умолчанию.</p>"],
    ["↻ Новое начало и rewind", "<p><code>/reset</code> начинает новую сессию в той же теме, сохраняя профиль, сервер и папку. Предыдущая сессия остаётся в OpenCodez.</p><p><code>/reset solm</code> одновременно выбирает другой профиль.</p><blockquote><b>Ответ на старый пользовательский запрос — rewind.</b> Бот отменяет последующую ветку и отправляет твой ответ вместо того запроса. Это не обычное цитирование.</blockquote><p><code>/context</code> выгружает последние завершённые или прерванные ходы. <code>/context 1</code> берёт один ход. Технические compaction и reminders не становятся отдельными запросами.</p>"],
    ["📎 Файлы и 🎙 аудио", "<p>FILES получает результаты, которые агент отправляет по твоей просьбе. Брось туда файл, чтобы сохранить его на настроенном сервере; бот вернёт путь.</p><p>AUDIO распознаёт голосовые и аудиофайлы. Текст можно скопировать и отправить агенту самостоятельно.</p><blockquote>Расшифровка голосового никогда не запускает агента автоматически.</blockquote><p>Подключи Groq через Setup. Рекомендуемая модель — Whisper Large V3 Turbo. Бесплатный тариф имеет ограничения.</p><p>Озвучка ответов — отдельная функция в настройках. <code>/speak</code> на ответе запрашивает одноразовую озвучку, если провайдеры настроены.</p>"],
    ["⚙ Настройки и уведомления", "<p>Уведомления о завершении, вопросах и сбоях приходят в личку. Один раз открой чат с ботом и нажми Start. Уведомления о завершении можно отключить в настройках.</p><p><code>/setup</code> проверяет подключения и продолжает незавершённую настройку. Повторный запуск не создаёт служебные темы заново.</p><p>Язык, отображение инструментов и параметры озвучки находятся в General → Настройки. <code>/update</code> проверяет обновления бота.</p><blockquote>Панель General обновляется на новом месте раз в сутки. <code>/menu</code> переносит её вниз немедленно.</blockquote>"],
  ],
  en: [
    ["✦ Welcome", "<p>General is for creating topics and configuring the bot. A working topic is a conversation with your OpenCodez agent.</p><blockquote>Press <b>New topic</b>, check the title and model, create the topic, and start writing.</blockquote><p>The default name is a random Old Russian word. Another word draws again; Title lets you enter your own. Disable the mode in Settings.</p><p>FILES collects files. AUDIO turns voice notes and audio files into text. You can finish these connections later.</p>"],
    ["🎛 Topics and profiles", "<p>A profile saves the model, reasoning, and optional System and agent. Create, copy, edit, delete and restore profiles in General → Profiles.</p><p>The catalog comes from the selected OpenCodez server. Models are grouped by provider and family. Search accepts names and IDs.</p><blockquote>Saving a profile does not change running sessions. New topics use the selected settings.</blockquote><p><code>/new</code> opens the wizard. <code>/new sol Title</code> remains a quick creation command.</p>"],
    ["💬 Everyday work", "<p>Send your prompt in its topic. Attach images or files. Files without captions wait for your next text message.</p><table striped compact><tr><th>Command</th><th>Action</th></tr><tr><td>/session</td><td>Model, status and OpenCodez link</td></tr><tr><td>/q prompt</td><td>Send or queue a prompt</td></tr><tr><td>/q status</td><td>View the queue</td></tr><tr><td>/kill</td><td>Stop and clear the queue</td></tr><tr><td>/compact</td><td>Compact an idle session</td></tr></table><p>The bot shows agent text and final answers. Ordinary tool actions are hidden by default.</p>"],
    ["↻ Reset and rewind", "<p><code>/reset</code> starts a new session in the same topic, keeping its profile, server and directory. The previous session remains in OpenCodez.</p><p><code>/reset solm</code> also selects another profile.</p><blockquote><b>Replying to an earlier user prompt rewinds that turn.</b> The bot discards the later branch and submits your reply in place of that prompt. This is not ordinary quoting.</blockquote><p><code>/context</code> exports recent completed or interrupted turns. <code>/context 1</code> exports one. Internal compaction and reminders do not count as separate prompts.</p>"],
    ["📎 Files and 🎙 audio", "<p>FILES receives results the agent sends at your request. Drop a file there to save it on the configured server; the bot returns its path.</p><p>AUDIO transcribes voice notes and audio files. Copy the text and send it to the agent yourself.</p><blockquote>A transcript never starts an agent automatically.</blockquote><p>Connect Groq through Setup. Whisper Large V3 Turbo is recommended. The free tier has limits.</p><p>Spoken answers are a separate setting. Reply <code>/speak</code> to an answer for a one-off voice summary when providers are configured.</p>"],
    ["⚙ Settings and notifications", "<p>Final-answer, question and failure alerts arrive in your private chat. Open the bot and press Start once. Final-answer notifications can be disabled in settings.</p><p><code>/setup</code> checks connections and continues unfinished setup. Running it again does not recreate service topics.</p><p>Language, tool visibility and voice options are in General → Settings. <code>/update</code> checks bot updates.</p><blockquote>The General panel moves to a fresh message daily. <code>/menu</code> moves it to the bottom immediately.</blockquote>"],
  ],
}

export function guidePage(index = 0, language = "en") {
  const list = pages[language] || pages.en
  const page = Math.max(0, Math.min(index, list.length - 1))
  const [title, body] = list[page]
  return { html: `<h2>${title}</h2>${body}${guideDetails(page, language)}<footer>${page + 1} / ${list.length}</footer>`, total: list.length }
}

export function guideDocument(language = "en") {
  return (pages[language] || pages.en).map(([title, body], index) => `<section><h1>${title}</h1>${body}${guideDetails(index, language)}</section>`).join("\n")
}

function guideDetails(index, language) {
  const ru = language === "ru"
  if (index === 2) return `<p>${ru ? "<code>/q delete N</code> убирает элемент очереди по номеру. Вопросы агента показываются кнопками; работа продолжится после твоего ответа." : "<code>/q delete N</code> removes a queue item by number. Agent questions use buttons; work continues after your answer."}</p>`
  if (index === 3) return `<p>${ru ? "Глубину /context можно сохранить в личных настройках или командой <code>/set_context N</code>, от 1 до 10." : "Save your /context depth in personal settings or with <code>/set_context N</code>, from 1 to 10."}</p>`
  if (index === 5) return `<details><summary>${ru ? "Дополнительные возможности" : "Advanced options"}</summary><p>${ru ? "Автоматические напоминания исходного запроса после compaction включены по умолчанию. Их переключатель находится в дополнительных настройках; <code>/reminder on|off</code> — быстрый способ. Там же можно показать действия инструментов и добавить диагностику в личные уведомления. Озвучка ответов имеет отдельные настройки профиля, голоса, длины и инструкции суммаризации." : "Original-prompt reminders after automatic compaction are enabled by default. Change them in advanced settings or with <code>/reminder on|off</code>. You can also show tool actions and add diagnostics to private notifications. Spoken answers have separate synthesis-profile, voice, length and summary-prompt settings."}</p></details>`
  return ""
}
